SELECT ANIMAL_ID, NAME 
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT I.ANIMAL_ID
                FROM ANIMAL_INS AS I JOIN ANIMAL_OUTS AS O 
                ON I.ANIMAL_ID = O.ANIMAL_ID)
ORDER BY 1 ASC;