SELECT UGU.USER_ID AS USER_ID, UGU.NICKNAME AS NICKNAME, 
CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS '전체주소', 
CONCAT(SUBSTRING(UGU.TLNO,1,3), "-",SUBSTRING(UGU.TLNO,4,4), "-",SUBSTRING(UGU.TLNO,8,4)) AS '전화번호'
FROM USED_GOODS_BOARD AS UGB JOIN USED_GOODS_USER AS UGU
ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY 1
HAVING COUNT(*) >= 3
ORDER BY 1 DESC;
       
       