WITH RECURSIVE CTE(HOUR) AS (
SELECT 0
UNION ALL
SELECT HOUR+1 FROM CTE WHERE HOUR < 23)
SELECT HOUR, COUNT(HOUR(DATETIME)) AS 'COUNT'
FROM CTE LEFT JOIN ANIMAL_OUTS
ON CTE.HOUR = HOUR(DATETIME) GROUP BY HOUR;