SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) IN (8,9,10) GROUP BY CAR_ID
    HAVING COUNT(*) >=5) AND MONTH(START_DATE) IN (8,9,10)
GROUP BY MONTH, CAR_ID
ORDER BY 1 ASC, 2 DESC;