SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (B.SIZE - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID 
FROM ECOLI_DATA AS A LEFT JOIN (SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as SIZE FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) AS B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY 1 ASC, 2 ASC;