SELECT HD.DEPT_ID AS DEPT_ID, HD.DEPT_NAME_EN AS DEPT_NAME_EN, ROUND(AVG(HE.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT AS HD JOIN HR_EMPLOYEES AS HE
ON HD.DEPT_ID = HE.DEPT_ID
GROUP BY HE.DEPT_ID
ORDER BY 3 DESC;