SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS B INNER JOIN BOOK_SALES AS BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE) = 1
GROUP BY 1 ORDER BY 1 ASC;